FROM python:3.11-slim
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1 PIP_NO_CACHE_DIR=1
ENV TZ=Europe/Moscow

WORKDIR /app
COPY requirements.txt ./
RUN pip install --upgrade pip && pip install -r requirements.txt

# Непривилегированный пользователь
RUN useradd -m appuser
USER appuser

COPY --chown=appuser:appuser . .

# ВАЖНО: путь к SQLite внутри контейнера
ENV DATABASE_URL=sqlite:////app/database.db

# Uvicorn достаточно для старта
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--proxy-headers"]
