services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      network: host
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
      network: host
    environment:
      - DEPARTMENT_NAME="Технический блок"
      - DATABASE_URL=sqlite:////db/database.db   
    volumes:
      - /srv/tasks-db:/db                        
    expose:
      - "8000"
    restart: unless-stopped

  tg_bot:
    build:
      context: ../tg_bot
      dockerfile: Dockerfile
      network: host         
    environment:
      - API_BASE=http://backend:8000
    env_file:
      - ../.env
    depends_on:
      - backend
    restart: unless-stopped